### ISSUE TITLE
Mention kms-env

### ISSUE THREAD

**Issue by calvinlfer** [ukayani/ecs-service#7]
This section https://github.com/ukayani/ecs-service#supplying-environment-variables-to-your-docker-service mentions how to use normal environment variables, but it would be nice to mention how ecs-service composes extremely well with [kms-env](https://github.com/ukayani/kms-env) to allow secure environment variables. Perhaps a small write-up or link to the repository would suffice?

**Comment by ukayani** [comment]
I've included a small reference to it. Thanks
